services:
  reports-java:
    build:
      context: ./experimental/reports-java
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://postgres/planner
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: planner

  scheduler-cpp:
    build:
      context: ./experimental/scheduler-cpp
      dockerfile: Dockerfile

networks:
  default:
    external: true
    name: ai-planner-network
